version: '2.4'
services:
  agent:
    image: pedominguezbr/vstsagentewin:2.195.1
    environment:
      - AZP_TOKEN=kj4zx3bmkzxecru6meqyeqofqmw5gohygk7iywzyr5vgddy42jq
      - AZP_AGENT_NAME=pedominguezbr_vstsagent
      - AZP_URL=https://dev.azure.com/aksdemo1pd
      - AZP_POOL=pedominguezbr_pool
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
